# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
